#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Jun 26 00:02:02 2011

import wx
from app import wxDomeTrackerFrame

class DomeTrackerAppClass(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frmMain = wxDomeTrackerFrame.wxDomeTrackerFrame(None, -1, "")
        self.SetTopWindow(frmMain)
        frmMain.Show()
        
        return 1
        
if __name__ == "__main__":
    wxDomeTracker = DomeTrackerAppClass(0)
    wxDomeTracker.MainLoop()
